### ISSUE TITLE
你好，服务器这块我不是很懂，有些问题请教

### ISSUE THREAD

**Issue by LoveqLRC** [375670450/PDFViewerServer#1]
我用webstorm导入了该项目后，运行后，发送一个请求，打断点就是进入不到Account.findOne的方法，是我哪里配置错误了吗？

**Comment by LoveqLRC** [comment]
是不是没有Account.findOne的方法，还是代码不全？

**Comment by stardust95** [comment]
Account.findOne方法是mongoose库提供的, 不需要自己写或者调试,
如果想看结果的话, 可以在routes/accounts.js文件第20~28行, 即Account.findOne的回调函数里下断点调试
